For Text Mining assignment
 
 ONE:
1) Perform sentimental analysis on the Elon-musk tweets (Exlon-musk.csv)

 TWO:
1) Extract reviews of any product from ecommerce website like amazon
2) Perform emotion mining

In [1]:
pip install  textblob

Collecting textblob
  Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 636.8/636.8 kB 6.9 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: nltk>=3.1 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from textblob) (3.7)
Requirement already satisfied: regex>=2021.8.3 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from nltk>=3.1->textblob) (2022.7.9)
Requirement already satisfied: joblib in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from nltk>=3.1->textblob) (1.1.1)
Requirement already satisfied: click in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from nltk>=3.1->textblob) (8.0.4)
Requirement already satisfied: tqdm in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from nltk>=3.1->textblob) (4.64.1)
Installing collected packages: textblob
Successfully installed textblob-0.17.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import re
import warnings
warnings.filterwarnings("ignore")

In [3]:
dt=pd.read_csv("Elon_musk.csv",encoding='unicode_escape')

In [4]:
dt

      Unnamed: 0                                               Text
0              1                             @kunalb11 Im an alien
1              2  @ID_AA_Carmack Ray tracing on Cyberpunk with H...
2              3                @joerogan @Spotify Great interview!
3              4                    @gtera27 Doge is underestimated
4              5  @teslacn Congratulations Tesla China for amazi...
...          ...                                                ...
1994        1995  @flcnhvy True, it sounds so surreal, but the n...
1995        1996  @PPathole Make sure to read ur terms &amp; con...
1996        1997                @TeslaGong @PPathole Samwise Gamgee
1997        1998  @PPathole Altho Dumb and Dumber is <U+0001F525...
1998        1999                          Progress update August 28

[1999 rows x 2 columns]

# EDA

In [5]:
dt.isna().sum()

Unnamed: 0    0
Text          0
dtype: int64

In [6]:
dt.duplicated().sum()

0

In [7]:
dt=dt.drop(columns=('Unnamed: 0'),axis=1)

In [8]:
dt

                                                   Text
0                                @kunalb11 Im an alien
1     @ID_AA_Carmack Ray tracing on Cyberpunk with H...
2                   @joerogan @Spotify Great interview!
3                       @gtera27 Doge is underestimated
4     @teslacn Congratulations Tesla China for amazi...
...                                                 ...
1994  @flcnhvy True, it sounds so surreal, but the n...
1995  @PPathole Make sure to read ur terms &amp; con...
1996                @TeslaGong @PPathole Samwise Gamgee
1997  @PPathole Altho Dumb and Dumber is <U+0001F525...
1998                          Progress update August 28

[1999 rows x 1 columns]

# preprocessing

In [9]:
dt.Text=dt.Text.apply(lambda x: re.sub('[^a-zA-Z]',"",x))

In [10]:
dt

                                                   Text
0                                       kunalbImanalien
1     IDAACarmackRaytracingonCyberpunkwithHDRisnextl...
2                         joeroganSpotifyGreatinterview
3                             gteraDogeisunderestimated
4     teslacnCongratulationsTeslaChinaforamazingexec...
...                                                 ...
1994  flcnhvyTrueitsoundssosurrealbutthenegativeprop...
1995  PPatholeMakesuretoreadurtermsampconditionsbefo...
1996                     TeslaGongPPatholeSamwiseGamgee
1997                   PPatholeAlthoDumbandDumberisUFUF
1998                               ProgressupdateAugust

[1999 rows x 1 columns]

In [11]:
dt.Text=dt.Text.apply(lambda x: x.lower())

In [12]:
dt

                                                   Text
0                                       kunalbimanalien
1     idaacarmackraytracingoncyberpunkwithhdrisnextl...
2                         joeroganspotifygreatinterview
3                             gteradogeisunderestimated
4     teslacncongratulationsteslachinaforamazingexec...
...                                                 ...
1994  flcnhvytrueitsoundssosurrealbutthenegativeprop...
1995  ppatholemakesuretoreadurtermsampconditionsbefo...
1996                     teslagongppatholesamwisegamgee
1997                   ppatholealthodumbanddumberisufuf
1998                               progressupdateaugust

[1999 rows x 1 columns]

In [13]:
dt.Text=dt.Text.apply(lambda x: x.split())

In [14]:
dt

                                                   Text
0                                     [kunalbimanalien]
1     [idaacarmackraytracingoncyberpunkwithhdrisnext...
2                       [joeroganspotifygreatinterview]
3                           [gteradogeisunderestimated]
4     [teslacncongratulationsteslachinaforamazingexe...
...                                                 ...
1994  [flcnhvytrueitsoundssosurrealbutthenegativepro...
1995  [ppatholemakesuretoreadurtermsampconditionsbef...
1996                   [teslagongppatholesamwisegamgee]
1997                 [ppatholealthodumbanddumberisufuf]
1998                             [progressupdateaugust]

[1999 rows x 1 columns]

# Removing stop words

In [15]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kishoresuddapalli/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [16]:
stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [17]:
dt.Text=dt.Text.apply(lambda x: [word for word in x if word not in set (stopwords.words('english'))])

In [18]:
dt

                                                   Text
0                                     [kunalbimanalien]
1     [idaacarmackraytracingoncyberpunkwithhdrisnext...
2                       [joeroganspotifygreatinterview]
3                           [gteradogeisunderestimated]
4     [teslacncongratulationsteslachinaforamazingexe...
...                                                 ...
1994  [flcnhvytrueitsoundssosurrealbutthenegativepro...
1995  [ppatholemakesuretoreadurtermsampconditionsbef...
1996                   [teslagongppatholesamwisegamgee]
1997                 [ppatholealthodumbanddumberisufuf]
1998                             [progressupdateaugust]

[1999 rows x 1 columns]

# stemming

In [19]:
pp = PorterStemmer()
dt.Text=dt.Text.apply(lambda x:[pp.stem(word) for word in x])

In [20]:
dt

                                                   Text
0                                     [kunalbimanalien]
1     [idaacarmackraytracingoncyberpunkwithhdrisnext...
2                       [joeroganspotifygreatinterview]
3                               [gteradogeisunderestim]
4     [teslacncongratulationsteslachinaforamazingexe...
...                                                 ...
1994  [flcnhvytrueitsoundssosurrealbutthenegativepro...
1995  [ppatholemakesuretoreadurtermsampconditionsbef...
1996                    [teslagongppatholesamwisegamge]
1997                 [ppatholealthodumbanddumberisufuf]
1998                             [progressupdateaugust]

[1999 rows x 1 columns]

# Rejoining

In [21]:
dt.Text=dt.Text.apply(lambda x:"".join(x))

In [22]:
dt

                                                   Text
0                                       kunalbimanalien
1     idaacarmackraytracingoncyberpunkwithhdrisnextl...
2                         joeroganspotifygreatinterview
3                                 gteradogeisunderestim
4     teslacncongratulationsteslachinaforamazingexec...
...                                                 ...
1994  flcnhvytrueitsoundssosurrealbutthenegativeprop...
1995  ppatholemakesuretoreadurtermsampconditionsbefo...
1996                      teslagongppatholesamwisegamge
1997                   ppatholealthodumbanddumberisufuf
1998                               progressupdateaugust

[1999 rows x 1 columns]

# sentiment Analysis

In [23]:
from textblob import TextBlob
dt['sentiment']= dt['Text'].apply(lambda x: TextBlob(x).sentiment[0] )
dt[['Text','sentiment']].head()

                                                Text  sentiment
0                                    kunalbimanalien        0.0
1  idaacarmackraytracingoncyberpunkwithhdrisnextl...        0.0
2                      joeroganspotifygreatinterview        0.0
3                              gteradogeisunderestim        0.0
4  teslacncongratulationsteslachinaforamazingexec...        0.0

# statement-2

In [24]:
import requests
from bs4 import BeautifulSoup
import seaborn as sns
import matplotlib.pyplot as plt

In [25]:
link='https://www.amazon.in/Kindle-10th-Gen/product-reviews/B07FQ4Q7MB/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews'

In [26]:

review_list=[]

for k in range(0,6):
    review_link=link+'&pageNumber='+str(k)
    print(review_link)
    page=requests.get(review_link)
    soup=BeautifulSoup(page.content,'html.parser')
    reviews=soup.find_all('span',class_='review-text-content')
    
    for i in range(0,len(reviews)):
        
        review_list.append(reviews[i].get_text().strip())

https://www.amazon.in/Kindle-10th-Gen/product-reviews/B07FQ4Q7MB/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=0
https://www.amazon.in/Kindle-10th-Gen/product-reviews/B07FQ4Q7MB/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=1
https://www.amazon.in/Kindle-10th-Gen/product-reviews/B07FQ4Q7MB/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2
https://www.amazon.in/Kindle-10th-Gen/product-reviews/B07FQ4Q7MB/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3
https://www.amazon.in/Kindle-10th-Gen/product-reviews/B07FQ4Q7MB/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=4
https://www.amazon.in/Kindle-10th-Gen/product-reviews/B07FQ4Q7MB/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=5

In [27]:
review_list

[]

In [28]:
len(review_list)

0

In [29]:
rv=pd.DataFrame({'Reviews':review_list})
pd.set_option('max_colwidth', 800)
rv

Empty DataFrame
Columns: [Reviews]
Index: []

# preprocessing

In [30]:
import nltk  
nltk.download('stopwords') 
from nltk.corpus import stopwords  
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kishoresuddapalli/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [31]:
stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [32]:
pp=PorterStemmer()

In [33]:
def rvpreprocess(x):
         x=re.sub('[^a-zA-Z ]', "", x)
         x=x.lower()
         x=x.split()  
         x=[word  for word in x if word not in set(stopwords.words('english'))]  
         x=[pp.stem(word) for word in x] 
         x=" ".join(x)
         return x

In [34]:
rv["Reviews"]=rv["Reviews"].apply(rvpreprocess)

In [35]:
rv.head()

Empty DataFrame
Columns: [Reviews]
Index: []

In [36]:
pip install wordcloud

Collecting wordcloud
  Downloading wordcloud-1.9.2.tar.gz (222 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.8/222.8 kB 5.1 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.6.1 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from wordcloud) (1.23.5)
Requirement already satisfied: pillow in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from wordcloud) (9.4.0)
Requirement already satisfied: matplotlib in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from wordcloud) (3.7.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from matplotlib->wordcloud) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from matplotlib->wordcloud) (22.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from matplotlib->wordcloud) (1.0.5)
Requirement already satisfied: six>=1.5 in /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-310
      creating build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/_version.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/__init__.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/tokenization.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/wordcloud.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/color_from_image.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/__main__.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/stopwords -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      UPDATING build/lib.macosx-11.1-arm64-cpython-310/wordcloud/_version.py
      set build/lib.macosx-11.1-arm64-cpython-310/wordcloud/_version.py to '1.9.2'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build/temp.macosx-11.1-arm64-cpython-310
      creating build/temp.macosx-11.1-arm64-cpython-310/wordcloud
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/kishoresuddapalli/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/kishoresuddapalli/anaconda3/include -arch arm64 -I/Users/kishoresuddapalli/anaconda3/include/python3.10 -c wordcloud/query_integral_image.c -o build/temp.macosx-11.1-arm64-cpython-310/wordcloud/query_integral_image.o
      xcode-select: note: No developer tools were found, requesting install.
      If developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.
      See `man xcode-select` for more details.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install
      /Users/kishoresuddapalli/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-310
      creating build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/_version.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/__init__.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/tokenization.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/wordcloud.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/color_from_image.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/__main__.py -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/stopwords -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-11.1-arm64-cpython-310/wordcloud
      UPDATING build/lib.macosx-11.1-arm64-cpython-310/wordcloud/_version.py
      set build/lib.macosx-11.1-arm64-cpython-310/wordcloud/_version.py to '1.9.2'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build/temp.macosx-11.1-arm64-cpython-310
      creating build/temp.macosx-11.1-arm64-cpython-310/wordcloud
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/kishoresuddapalli/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/kishoresuddapalli/anaconda3/include -arch arm64 -I/Users/kishoresuddapalli/anaconda3/include/python3.10 -c wordcloud/query_integral_image.c -o build/temp.macosx-11.1-arm64-cpython-310/wordcloud/query_integral_image.o
      xcode-select: note: No developer tools were found, requesting install.
      If developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.
      See `man xcode-select` for more details.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Note: you may need to restart the kernel to use updated packages.

In [37]:
from wordcloud import WordCloud
wordcloud = WordCloud(height=2000, width=2000,max_words=100, background_color='white')
wordcloud = wordcloud.generate(' '.join(rv['Reviews'].tolist()))
plt.figure(figsize=(15,15),dpi=50)
plt.imshow(wordcloud)
plt.title("Most common words in the reviews")
plt.axis('off')
plt.show()

ModuleNotFoundError: No module named 'wordcloud'

# Sentiment Analysis

In [ ]:
from textblob import TextBlob
rv['sentiment_score'] = rv['Reviews'].apply(lambda x: TextBlob(x).sentiment[0] )
rv[['Reviews','sentiment_score']].head()

In [ ]:
## Defining function to assign sentiment category based on sentiment_score
## Score Range -0.5 to 0.5 is considered as neutral
def sentiment_category(score1):
    if(score1 > 0.5):
        return 'Positive'
    elif(score1 < -0.5):
        return 'Negative'
    else:
        return 'Neutral'

In [ ]:
rv['sentiment'] = rv['sentiment_score'].apply(lambda x:sentiment_category(x))

In [ ]:
rv.head()

In [ ]:
rv['sentiment'].value_counts()

In [ ]:
sns.countplot(x=rv['sentiment'])